Add kubectl
swaglive/actions pull request #5
Opened 2020-02-03 09:04 UTC by RammusXu

2020-02-04 10:04 UTC, allanlei requested changes

2020-02-04 10:04 UTC, allanlei commented on kubectl/Dockerfile
> +FROM gcr.io/cloud-builders/kubectl@sha256:1023dbcb23ff0776891bd9ed3e3d1e83d35f4c274d8dc2f2017490bfcba38da3
Use a different kubectl.  too fat

2020-05-26 02:39 UTC, RammusXu commented on kubectl/Dockerfile
> +FROM gcr.io/cloud-builders/kubectl@sha256:1023dbcb23ff0776891bd9ed3e3d1e83d35f4c274d8dc2f2017490bfcba38da3
Change it to `swaglive/kubectl:1.17`

2020-06-23 05:44 UTC, RammusXu commented
Close #7

2020-06-23 09:57 UTC, allanlei requested changes
Needs to be more Unix like.   `Write programs that do one thing and do it well`.

2020-06-24 09:30 UTC, allanlei approved these changes

2020-06-24 09:30 UTC, merged